name: Docker Build Workflow

on:
  push:
    tags: v*.*.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: ./
        with:
          image_name: a2barros78/muhmuh
          tag: ${{ github.sha }}
          context: '.'
